version: '3'

services:
  frontend:
    image: frontend
    build: ./frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./frontend/src:/usr/src/app/src
      - ./frontend/public:/usr/src/app/public
      - ./frontend/package.json:/usr/src/app/package.json
      - ./frontend/yarn.lock:/usr/src/app/yarn.lock
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_PASSWORD=development
  backend:
    depends_on:
      - db
    image: blank
    build: ./backend
    restart: always
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=development
    volumes:
      - ./backend:/usr/src/app
