# Generated by Django 2.2.6 on 2019-11-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='', upload_to='uploads/avatars'),
            preserve_default=False,
        ),
    ]
